### ISSUE TITLE
3.0.2 tagged but no release?

### ISSUE THREAD

**Issue by criztovyl** [inveniosoftware-contrib/intbitset#94]
is it intentional that a 3.0.2 tag exists, but no github release?

**Comment by criztovyl** [comment]
ah, and pypi also has 3.0.2 already. :)

**Comment by pombredanne** [comment]
@criztovyl Thanks... that's an oversight. I will fix this. This is tagged, but no additional "release" was done.

**Comment by pombredanne** [comment]
Fixed now https://github.com/inveniosoftware-contrib/intbitset/releases/tag/v3.0.2 :)
